import Link from 'next/link';
import { ArrowUpRight, ImageIcon, ShoppingBag, MessageCircle } from 'lucide-react';
import { imageUrl, formatPrice, type Product, type Shop } from '../data';
import { AddToCart, CartCount } from './[slug]/panier/cart';
import { whatsappProductUrl } from './whatsapp';
export function shopStyle(color:string):React.CSSProperties{const hex=/^#[0-9a-f]{6}$/i.test(color)?color:'#176b7a';const rgb=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);const luminance=.2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];return {'--shop-accent':hex,'--shop-on-accent':luminance>.179?'#102634':'#ffffff'} as React.CSSProperties}
export function ShopHeader({shop}:{shop:Shop}){return <header className="store-header"><Link className="store-brand" href={'/boutique/'+shop.slug}>{shop.avatar_key?<img src={imageUrl(shop.avatar_key)!} alt=""/>:<span className="store-monogram">{shop.name[0]}</span>}<span>{shop.name}</span></Link><nav aria-label="Navigation de la boutique"><Link className="store-catalog-link" href={'/boutique/'+shop.slug+'#catalogue'}>Collection</Link><CartCount slug={shop.slug}/></nav></header>}
export function ProductCard({product:p,slug,whatsappNumber}:{product:Product;slug:string;whatsappNumber?:string|null}){const whatsapp=whatsappProductUrl(whatsappNumber,p);return <article className="store-product"><Link className="store-product-image" href={'/boutique/'+slug+'/produit/'+p.id} aria-label={'Découvrir '+p.name}>{p.image_key?<img src={imageUrl(p.image_key)!} alt={p.name} loading="lazy"/>:<div className="store-image-empty"><ImageIcon size={38} strokeWidth={1.2}/><span>Photo à venir</span></div>}<span className="store-product-discover"><ArrowUpRight size={20}/></span></Link><div className="store-product-body"><h3><Link href={'/boutique/'+slug+'/produit/'+p.id}>{p.name}</Link></h3><strong>{formatPrice(p.price,p.currency)}</strong>{p.description&&<p>{p.description}</p>}<div className="store-product-actions"><AddToCart slug={slug} id={p.id}/>{whatsapp&&<a className="store-whatsapp-button" href={whatsapp} target="_blank" rel="noopener noreferrer" aria-label={'Commander '+p.name+' sur WhatsApp'}><MessageCircle size={16}/> WhatsApp</a>}</div></div></article>}
export function StoreFooter({shop}:{shop:Shop}){return <footer className="store-footer"><div><strong>{shop.name}</strong><p>Votre sélection, directement auprès du vendeur.</p></div><Link href="/"><ShoppingBag size={16}/> Propulsé par MaVitrine</Link></footer>}
