import Link from 'next/link';
import { ArrowRight, ShoppingBag, Store, Tag, ChartNoAxesColumnIncreasing, Package, Palette, ClipboardList, Link2, CheckCircle2 } from 'lucide-react';
import { getChatGPTUser, chatGPTSignInPath } from './chatgpt-auth';
import Pricing from './pricing';
import LandingFaq from './landing-faq';
import MobileMenu from './mobile-menu';
export default async function Home() {
  const user = await getChatGPTUser();
  const dashboard = user ? '/dashboard' : chatGPTSignInPath('/dashboard');
  return <main className="landing-page">
    <header className="landing-header">
      <Link className="landing-logo" href="/" aria-label="Ma Vitrine, accueil"><img className="mavitrine-mark" src="/mavitrine-logo.png" alt="" width="48" height="48"/><span className="landing-logo-copy"><strong>mavitrine</strong><small>Des créateurs. Des histoires. Une même vitrine.</small></span></Link>
      <nav aria-label="Navigation principale"><Link href="/boutiques">Découvrir</Link><a href="#fonctionnalites">Fonctionnalités</a><a href="#tarifs">Tarifs</a><Link href={dashboard}>{user ? 'Mon espace' : 'Se connecter'}</Link><Link className="landing-header-cta" href={dashboard}>Créer ma boutique <ArrowRight size={18}/></Link></nav><MobileMenu dashboard={dashboard}/>
    </header>
    <section className="landing-hero"><div className="landing-hero-copy"><p className="landing-overline">VOTRE ESPACE DE VENTE</p><h1>Votre boutique, <span>votre univers.</span></h1><p>Créez votre vitrine, présentez vos produits et gérez vos commandes.</p><div className="landing-actions"><Link className="landing-primary" href={dashboard}>Créer ma boutique <ArrowRight size={21}/></Link><Link className="landing-secondary" href="/boutiques">Voir les boutiques</Link></div></div><div className="landing-showcase" role="img" aria-label="Aperçu illustratif du tableau de bord vendeur et d’une boutique avec catalogue"><img src="/landing-preview.png" alt="" fetchPriority="high"/></div><p className="preview-label">Aperçu illustratif de l’espace vendeur et de la vitrine client</p></section>
    <section className="landing-benefits" aria-label="En bref"><div className="landing-benefit"><span className="landing-benefit-icon"><Store size={25}/></span><div><h2>Créez facilement</h2><p>Votre boutique en quelques minutes.</p></div></div><div className="landing-benefit"><span className="landing-benefit-icon"><Tag size={25}/></span><div><h2>Mettez en valeur</h2><p>Vos créations et votre savoir-faire.</p></div></div><div className="landing-benefit"><span className="landing-benefit-icon"><ChartNoAxesColumnIncreasing size={25}/></span><div><h2>Gardez le contrôle</h2><p>Vos commandes au même endroit.</p></div></div></section>
    <section className="landing-section landing-features" id="fonctionnalites"><div className="section-intro"><span className="section-kicker">LES FONCTIONNALITÉS</span><h2>Tout pour vendre dans<br/>votre propre univers.</h2><p>Une boutique simple à personnaliser, un parcours clair pour vos clients et un espace pour suivre votre activité.</p></div><div className="feature-card-grid"><article><span className="feature-card-icon"><Store/></span><h3>Votre vitrine, votre identité</h3><p>Choisissez le nom, la couleur, le profil et la couverture de votre boutique. Partagez ensuite son lien personnel.</p></article><article><span className="feature-card-icon"><Package/></span><h3>Un catalogue à votre image</h3><p>Ajoutez les photos, les descriptions et les prix de vos produits depuis votre tableau de bord.</p></article><article><span className="feature-card-icon"><ShoppingBag/></span><h3>Un panier pour vos clients</h3><p>Les visiteurs sélectionnent leurs articles et confirment leur commande avec leurs coordonnées.</p></article><article><span className="feature-card-icon"><ClipboardList/></span><h3>Des commandes faciles à suivre</h3><p>Consultez les détails, changez le statut et indiquez quand le règlement a été reçu.</p></article></div></section>
    <section className="landing-section landing-how" id="comment-ca-marche"><div className="section-intro centered"><span className="section-kicker">COMMENT ÇA MARCHE</span><h2>Votre boutique en trois étapes.</h2><p>De votre idée à votre premier catalogue, sans configuration compliquée.</p></div><div className="steps-grid"><div><span>01</span><Store size={27}/><h3>Créez votre vitrine</h3><p>Choisissez un nom, un lien et les couleurs qui représentent votre activité.</p></div><div><span>02</span><Package size={27}/><h3>Ajoutez vos produits</h3><p>Présentez chaque article avec une photo, une description et un prix.</p></div><div><span>03</span><Link2 size={27}/><h3>Partagez et suivez</h3><p>Diffusez votre lien et retrouvez les commandes dans votre espace vendeur.</p></div></div></section>
    <section className="landing-section landing-pricing" id="tarifs"><div className="section-intro centered"><span className="section-kicker">TARIFS</span><h2>Une offre adaptée à votre rythme.</h2><p>Comparez les propositions mensuelles et annuelles.</p></div><Pricing dashboard={dashboard}/><p className="pricing-disclosure">Tarifs indicatifs pour la présentation du service. Aucun abonnement ni prélèvement n’est activé actuellement.</p></section>
    <section className="landing-section landing-testimonials" id="temoignages"><div className="section-intro centered"><span className="section-kicker">PAROLES DE CRÉATEURS</span><h2>Imaginez votre activité ici.</h2><p>Exemples de témoignages pour illustrer l’expérience. Ils seront remplacés par des avis vérifiés.</p></div><div className="testimonial-grid"><figure><blockquote>« Je peux présenter mes créations dans une boutique qui porte vraiment mon identité. »</blockquote><figcaption><span>AC</span><div><strong>Artisan créateur</strong><small>Exemple de témoignage</small></div></figcaption></figure><figure><blockquote>« Mes clients trouvent les produits, remplissent leur panier et je retrouve tout dans mon espace. »</blockquote><figcaption><span>BV</span><div><strong>Boutique indépendante</strong><small>Exemple de témoignage</small></div></figcaption></figure><figure><blockquote>« Le lien de ma boutique est simple à partager, et le suivi des commandes reste clair. »</blockquote><figcaption><span>CS</span><div><strong>Créatrice de produits</strong><small>Exemple de témoignage</small></div></figcaption></figure></div></section>
    <section className="landing-section landing-faq" id="questions"><div className="section-intro"><span className="section-kicker">QUESTIONS FRÉQUENTES</span><h2>Les réponses avant de vous lancer.</h2><p>Tout ce qu’il faut savoir pour ouvrir et partager votre boutique.</p></div><LandingFaq/></section>
    <section className="landing-final"><div><span className="section-kicker">C’EST À VOUS DE JOUER</span><h2>Votre prochaine vente commence avec votre vitrine.</h2><p>Créez votre boutique, ajoutez vos produits et partagez votre lien.</p></div><Link className="landing-primary" href={dashboard}>Créer ma boutique <ArrowRight size={20}/></Link></section>
    <footer className="landing-footer"><div><Link className="landing-footer-logo" href="/"><img className="mavitrine-mark" src="/mavitrine-logo.png" alt="" width="36" height="36"/> mavitrine</Link><p>Votre univers, votre boutique.</p></div><nav aria-label="Navigation de pied de page"><Link href="/boutiques">Boutiques</Link><a href="#fonctionnalites">Fonctionnalités</a><a href="#tarifs">Tarifs</a><a href="#questions">Questions</a></nav><small>© {new Date().getUTCFullYear()} Ma Vitrine</small></footer>
  </main>;
}
