import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ChevronRight, ImageIcon, ShoppingBag, ClipboardCheck, Wallet, MessageCircle } from 'lucide-react';
import { db,shopBySlug,shopProducts,formatPrice } from '../../../../data';
import ProductGallery from '../gallery';
import { AddToCart } from '../../panier/cart';
import { ShopHeader,ProductCard,StoreFooter,shopStyle } from '../../../shop-ui';
import { whatsappProductUrl } from '../../../whatsapp';
import MetaTracking from '../../../meta-tracking';
export const dynamic='force-dynamic';
export default async function Produit({params}:{params:Promise<{slug:string;id:string}>}){
 const {slug,id}=await params;let shop,products;
 try{shop=await shopBySlug(slug);if(shop)products=await shopProducts(shop.id)}catch{return <div className="alert error">Produit momentanément indisponible.</div>}
 if(!shop)notFound();const p=products?.find(p=>p.id===id);if(!p)notFound();const more=products?.filter(x=>x.id!==id).slice(0,3)||[];const gallery=(await db().prepare('SELECT image_key FROM product_images WHERE product_id=? AND shop_id=? ORDER BY position,id').bind(id,shop.id).all<{image_key:string}>()).results;const photos=[...(p.image_key?[p.image_key]:[]),...gallery.map(image=>image.image_key)];const whatsapp=whatsappProductUrl(shop.whatsapp_number,p);
 return <main className={'store-page theme-'+shop.surface_theme+' cards-'+shop.card_style} style={shopStyle(shop.accent_color)}><MetaTracking slug={slug} pixelId={shop.meta_pixel_id} productId={p.id}/><div className="store-container"><ShopHeader shop={shop}/><nav className="store-breadcrumb" aria-label="Fil d’Ariane"><Link href={'/boutique/'+slug}>Boutique</Link><ChevronRight size={14}/><Link href={'/boutique/'+slug+'#catalogue'}>Collection</Link><ChevronRight size={14}/><span aria-current="page">{p.name}</span></nav><section className="store-detail"><div className="store-detail-visual">{photos.length?<ProductGallery name={p.name} keys={photos}/>:<div className="store-image-empty"><ImageIcon size={64} strokeWidth={1}/><span>Photo à venir</span></div>}</div><div className="store-detail-info"><Link className="store-kicker" href={'/boutique/'+slug}>{shop.name}</Link><h1>{p.name}</h1><p className="store-detail-price">{formatPrice(p.price,p.currency)}</p><div className="store-description"><h2>À propos de ce produit</h2><p>{p.description||'Pour tout détail complémentaire, le vendeur vous accompagnera lors du suivi de votre commande.'}</p></div><div className="store-buy"><AddToCart slug={slug} id={p.id}/>{whatsapp&&<a className="store-whatsapp-button" href={whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/> Commander sur WhatsApp</a>}<Link className="store-view-cart" href={'/boutique/'+slug+'/panier'}>Voir mon panier <ShoppingBag size={17}/></Link></div><p className="store-buy-hint">Vérifiez votre panier avant de confirmer. Aucun prélèvement à cette étape.</p><div className="store-detail-notes"><div><ClipboardCheck size={21}/><span><strong>Commande suivie par le vendeur</strong><small>Vos coordonnées lui permettent de vous recontacter.</small></span></div><div><Wallet size={21}/><span><strong>Modalités de règlement</strong><small>{shop.payment_instructions||'Paiement à la livraison'}</small></span></div></div></div></section>{more.length>0&&<section className="store-related"><div className="store-section-heading"><div><span className="store-kicker">POUR CONTINUER LA DÉCOUVERTE</span><h2>Dans la même boutique</h2></div><Link href={'/boutique/'+slug+'#catalogue'}>Tout voir →</Link></div><div className="store-product-grid">{more.map(product=><ProductCard key={product.id} product={product} slug={slug} whatsappNumber={shop.whatsapp_number}/>)}</div></section>}<StoreFooter shop={shop}/></div></main>
}
