from typing import Any, Protocol

class Repository(Protocol):
    """Small persistence port; transaction lifetime belongs to the unit of work."""
    def get(self, model: type, identifier: str) -> Any: ...
    def one(self, model: type, **filters: Any) -> Any: ...
    def list(self, model: type, offset: int = 0, limit: int = 50, **filters: Any) -> list[Any]: ...
    def add(self, entity: Any) -> None: ...
    def delete(self, entity: Any) -> None: ...

class UnitOfWork(Protocol):
    repo: Repository
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
