"""cover_customization"""
from alembic import op
import sqlalchemy as sa

revision = '2de1af30b092'
down_revision = '843f3a206e4a'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_position', sa.Integer(), server_default='50', nullable=False))
        batch_op.add_column(sa.Column('cover_blur', sa.Integer(), server_default='2', nullable=False))
        batch_op.add_column(sa.Column('cover_shade', sa.Integer(), server_default='55', nullable=False))

    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_column('cover_shade')
        batch_op.drop_column('cover_blur')
        batch_op.drop_column('cover_position')

    # ### end Alembic commands ###
