import Link from 'next/link';
import { ArrowRight, Package, ClipboardList, Wallet, Plus, Store } from 'lucide-react';
import { sellerData, orderLines } from './shared';
import { imageUrl, formatPrice } from '../data';
export const dynamic='force-dynamic';
export default async function Dashboard({searchParams}:{searchParams:Promise<{message?:string}>}){let data;try{data=await sellerData('/dashboard')}catch{return <div className="alert error">Le tableau de bord est momentanément indisponible.</div>}const {user,shop,products,orders}=data;const {message}=await searchParams;const paidCount=orders.filter(o=>o.payment_status==='payé').length;return <><div className="seller-heading"><div><span className="seller-eyebrow">VUE D’ENSEMBLE</span><h1>Bonjour {user.fullName?.split(' ')[0]||'créateur'} 👋</h1><p>Voici l’activité de votre boutique.</p></div>{shop&&<Link className="seller-outline" href={'/boutique/'+shop.slug}>Voir ma boutique <ArrowRight size={17}/></Link>}</div>{message&&<div className="alert" role="status">{message}</div>}
 {!shop?<div className="seller-empty"><Store size={34}/><h2>Votre boutique commence ici</h2><p>Créez votre vitrine pour publier des produits et recevoir vos premières commandes.</p><Link className="seller-solid" href="/dashboard/boutique">Créer ma boutique <ArrowRight size={18}/></Link></div>:<><div className="seller-metrics"><div className="seller-metric"><span className="seller-metric-icon blue"><Package size={21}/></span><small>Produits en ligne</small><strong>{products.length}</strong><span className="seller-metric-note">Dans votre catalogue</span></div><div className="seller-metric"><span className="seller-metric-icon violet"><ClipboardList size={21}/></span><small>Commandes reçues</small><strong>{orders.length}</strong><span className="seller-metric-note">{orders.filter(o=>o.status==='nouvelle').length} nouvelle(s) à traiter</span></div><div className="seller-metric"><span className="seller-metric-icon cyan"><Wallet size={21}/></span><small>Commandes marquées payées</small><strong>{paidCount}</strong><span className="seller-metric-note">Marquage effectué par le vendeur</span></div></div>
 <div className="seller-section-head"><h2>Mes produits</h2><div><Link href="/dashboard/produits">Voir tout</Link><Link className="seller-solid small" href="/dashboard/produits/nouveau"><Plus size={16}/> Ajouter un produit</Link></div></div>{products.length?<div className="seller-table-scroll"><table className="seller-table"><thead><tr><th>Produit</th><th>Prix</th><th>Statut</th><th>Actions</th></tr></thead><tbody>{products.slice(0,4).map(p=><tr key={p.id}><td><div className="seller-product-cell">{p.image_key?<img src={imageUrl(p.image_key)!} alt=""/>:<span className="seller-thumb"><Package size={20}/></span>}<span><strong>{p.name}</strong><small>{p.description||'Sans description'}</small></span></div></td><td>{formatPrice(p.price,p.currency)}</td><td><span className="seller-status live">En ligne</span></td><td><Link className="seller-table-link" href={'/dashboard/produits/'+p.id}>Modifier ↗</Link></td></tr>)}</tbody></table></div>:<div className="seller-empty compact"><Package size={28}/><h3>Aucun produit</h3><p>Ajoutez votre premier produit au catalogue.</p><Link className="seller-solid small" href="/dashboard/produits/nouveau">Ajouter un produit</Link></div>}
 <div className="seller-section-head"><h2>Dernières commandes</h2><Link href="/dashboard/commandes">Voir tout</Link></div>{orders.length?<div className="seller-table-scroll"><table className="seller-table"><thead><tr><th>N°</th><th>Client</th><th>Produits</th><th>Montant</th><th>Statut</th><th>Date</th></tr></thead><tbody>{orders.slice(0,5).map(o=><tr key={o.id}><td><Link className="seller-table-link" href={'/dashboard/commandes/'+o.id}>#{o.id.slice(0,8).toUpperCase()}</Link></td><td>{o.customer_name}</td><td>{orderLines(o).reduce((n,item)=>n+item.quantity,0)} article(s)</td><td>{formatPrice(o.total,o.currency)}</td><td><span className={'seller-status '+(o.status==='terminée'?'done':o.status==='annulée'?'cancelled':'pending')}>{o.status}</span></td><td>{new Date(o.created_at).toLocaleDateString('fr-FR')}</td></tr>)}</tbody></table></div>:<div className="seller-empty compact"><ClipboardList size={28}/><h3>Aucune commande</h3><p>Partagez votre lien pour faire découvrir votre boutique.</p><Link className="seller-outline" href={'/boutique/'+shop.slug}>Ouvrir ma boutique <ArrowRight size={16}/></Link></div>}</>}</>}
