'use client';
import { useEffect,useState } from 'react';
import { Monitor,Smartphone,Sparkles,RotateCcw } from 'lucide-react';

type Options={accent:string;surface:string;align:string;height:string;card:string;columns:number};
const palette=['#176b7a','#245aa0','#274564','#6b4fb0','#0b746b','#b04c6f'];
const surfaces=[['blanc','Blanc pur'],['brume','Brume claire'],['glacier','Bleu glacier']] as const;
const heights=[['compact','Compact'],['standard','Équilibré'],['grand','Immersif']] as const;
const suggestions:{name:string;note:string;settings:Options}[]=[
 {name:'Studio glacier',note:'Une vitrine lumineuse qui met les photos en valeur.',settings:{accent:'#245aa0',surface:'glacier',align:'centre',height:'grand',card:'doux',columns:3}},
 {name:'Atelier brume',note:'Une composition apaisée pour les petites collections.',settings:{accent:'#176b7a',surface:'brume',align:'gauche',height:'standard',card:'doux',columns:2}},
 {name:'Édition graphique',note:'Un catalogue net, inspiré des boutiques éditoriales.',settings:{accent:'#274564',surface:'blanc',align:'gauche',height:'grand',card:'angle',columns:4}},
 {name:'Galerie douce',note:'Des produits généreux et un accueil centré.',settings:{accent:'#6b4fb0',surface:'blanc',align:'centre',height:'compact',card:'doux',columns:2}},
 {name:'Rivage',note:'Une palette fraîche et un catalogue équilibré.',settings:{accent:'#0b746b',surface:'glacier',align:'gauche',height:'standard',card:'doux',columns:3}}
];
function previewStyle(hex:string):React.CSSProperties{const rgb=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return {'--shop-accent':hex,'--shop-on-accent':.2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2]>.179?'#102634':'#fff'} as React.CSSProperties}
export default function StyleEditor({initial,name,description,cover,productImage}:{initial:Options;name:string;description:string;cover:string|null;productImage:string|null}){
 const [accent,setAccent]=useState(initial.accent),[surface,setSurface]=useState(initial.surface),[align,setAlign]=useState(initial.align),[height,setHeight]=useState(initial.height),[card,setCard]=useState(initial.card),[columns,setColumns]=useState(initial.columns),[device,setDevice]=useState<'desktop'|'mobile'>('desktop'),[previewName,setPreviewName]=useState(name),[previewDescription,setPreviewDescription]=useState(description);
 const [suggestionIndex,setSuggestionIndex]=useState(-1),[savedDraft,setSavedDraft]=useState<Options|null>(null);
 function applyStyle(options:Options){setAccent(options.accent);setSurface(options.surface);setAlign(options.align);setHeight(options.height);setCard(options.card);setColumns(options.columns)}
 function suggest(){if(suggestionIndex<0)setSavedDraft({accent,surface,align,height,card,columns});const next=(suggestionIndex+1)%suggestions.length;applyStyle(suggestions[next].settings);setSuggestionIndex(next)}
 useEffect(()=>{const input=document.getElementById('shop-name') as HTMLInputElement|null,desc=document.getElementById('shop-desc') as HTMLTextAreaElement|null;const sync=()=>{setPreviewName(input?.value||'Votre boutique');setPreviewDescription(desc?.value||'Présentez votre collection.')};input?.addEventListener('input',sync);desc?.addEventListener('input',sync);return()=>{input?.removeEventListener('input',sync);desc?.removeEventListener('input',sync)}},[]);
 return <section className="style-editor"><div className="style-editor-top"><div><span className="seller-eyebrow">DIRECTION VISUELLE</span><h2>Apparence de la boutique</h2><p>Choisissez l’ambiance de votre vitrine. L’aperçu se met à jour avant l’enregistrement.</p></div><div className="style-device" role="group" aria-label="Format de l’aperçu"><button type="button" aria-pressed={device==='desktop'} onClick={()=>setDevice('desktop')}><Monitor size={17}/> Ordinateur</button><button type="button" aria-pressed={device==='mobile'} onClick={()=>setDevice('mobile')}><Smartphone size={17}/> Mobile</button></div></div>
  <div className="style-suggestion"><div className="style-suggestion-icon"><Sparkles size={23}/></div><div><strong>{suggestionIndex<0?'Trouvez un style pour votre boutique':suggestions[suggestionIndex].name}</strong><p>{suggestionIndex<0?'Testez plusieurs ambiances en un clic, sans changer votre boutique en ligne.':suggestions[suggestionIndex].note}</p><span>Proposition {suggestionIndex<0?'—':(suggestionIndex+1)+' sur '+suggestions.length} · La boutique change seulement après « Enregistrer les modifications ».</span></div><div className="style-suggestion-actions"><button className="style-suggest-button" type="button" onClick={suggest}><Sparkles size={17}/>{suggestionIndex<0?'Essayer un style':'Tester un autre style'}</button>{suggestionIndex>=0&&<button className="style-reset-button" type="button" onClick={()=>{applyStyle(savedDraft||initial);setSavedDraft(null);setSuggestionIndex(-1)}}><RotateCcw size={16}/> Retrouver mes réglages</button>}</div></div>
  <div className="style-preview-stage"><div className={'style-preview '+device+' surface-'+surface+' align-'+align+' height-'+height+' card-'+card} style={{...previewStyle(accent),'--preview-cols':columns} as React.CSSProperties}><div className="style-preview-nav"><span className="style-preview-monogram">{previewName[0]||'B'}</span><strong>{previewName}</strong><span>Collection　 Panier</span></div><div className={'style-preview-hero '+(cover?'has-cover':productImage?'with-feature':'')} style={cover?{backgroundImage:'linear-gradient(90deg,rgba(7,25,38,.72),rgba(7,25,38,.32)),url('+JSON.stringify(cover)+')'}:undefined}><small>LA BOUTIQUE</small><strong>{previewName}</strong><p>{previewDescription||'Une sélection choisie avec soin.'}</p><span>Découvrir la collection →</span>{!cover&&productImage&&<div className="style-preview-feature"><img src={productImage} alt="Aperçu du produit mis en avant"/></div>}</div><div className="style-preview-collection"><div><small>DÉCOUVRIR</small><strong>La collection</strong></div><div className="style-preview-products">{Array.from({length:device==='mobile'?2:Math.min(columns,4)},(_,i)=><div key={i}><div className="style-preview-product-image">{i===0&&productImage?<img src={productImage} alt="Exemple de produit"/>:<span>Photo du produit</span>}</div><span>Votre produit</span><small>Voir le produit →</small></div>)}</div></div></div></div>
  <div className="style-option-group"><h3>Couleur principale</h3><p>Utilisée pour les boutons, liens et détails de la boutique.</p><div className="style-swatches">{palette.map(color=><button key={color} type="button" title={color} aria-label={'Utiliser la couleur '+color} aria-pressed={accent.toLowerCase()===color} onClick={()=>setAccent(color)} style={{background:color}}/>)}</div><label className="style-custom-color">Autre couleur <input type="color" name="accent_color" value={accent} onChange={e=>setAccent(e.target.value)}/><code>{accent.toUpperCase()}</code></label></div>
  <details className="style-advanced"><summary>Ajuster les détails à la main <span>Fond, couverture et grille de produits</span></summary>
  <div className="style-option-group"><h3>Fond de la boutique</h3><div className="style-choice-row">{surfaces.map(([value,label])=><label key={value} className="style-choice"><input type="radio" name="surface_theme" value={value} checked={surface===value} onChange={()=>setSurface(value)}/><span className={'style-surface-dot '+value}/>{label}</label>)}</div></div>
  <div className="style-option-split"><div className="style-option-group"><h3>Disposition de la couverture</h3><div className="style-choice-row">{([['gauche','Texte à gauche'],['centre','Texte centré']] as const).map(([value,label])=><label key={value} className="style-choice"><input type="radio" name="hero_align" value={value} checked={align===value} onChange={()=>setAlign(value)}/>{label}</label>)}</div></div><div className="style-option-group"><h3>Hauteur de la couverture</h3><div className="style-choice-row">{heights.map(([value,label])=><label key={value} className="style-choice"><input type="radio" name="hero_height" value={value} checked={height===value} onChange={()=>setHeight(value)}/>{label}</label>)}</div></div></div>
  <div className="style-option-split"><div className="style-option-group"><h3>Forme des photos</h3><div className="style-choice-row">{([['doux','Angles doux'],['angle','Angles droits']] as const).map(([value,label])=><label key={value} className="style-choice"><input type="radio" name="card_style" value={value} checked={card===value} onChange={()=>setCard(value)}/>{label}</label>)}</div></div><div className="style-option-group"><h3>Produits par ligne sur ordinateur</h3><div className="style-choice-row">{[2,3,4].map(value=><label key={value} className="style-choice"><input type="radio" name="catalog_columns" value={value} checked={columns===value} onChange={()=>setColumns(value)}/>{value} produits</label>)}</div><small>Sur mobile, la grille s’adapte automatiquement à l’écran.</small></div></div></details>
 </section>
}
